#!/usr/bin/env sh
zsh="$HOME/.oh-my-zsh"
dotfiles="$HOME/.files"
repos="https://github.com/jimzhan/dotfiles.git"

Xcode=$HOME/Library/Developer/Xcode
XcodeKeys=$Xcode/UserData/KeyBindings
XcodeThemes=$Xcode/UserData/FontAndColorThemes
XcodeTemplates=$Xcode/Templates

# to error out
warn() {
  echo "$1" >&2
}

die() {
  warn "$1"
  exit 1
}

# forcely remove any existing link or directory.
deldir() {
  if [ -L $1 ]; then
    unlink "$1"
  elif [ -d $1 ]; then
    rm -rf "$1"
  fi
}

# forcely remove any existing link or file before creating custom links.
link() {
  if [ -h $2 ] ; then
    unlink $2
  elif [ -e $2 ]; then
    rm $2
  fi
  ln -s $1 $2
}

# setup Xcode's themes & file/project templates.
setup_xcode() {
  if [ -d $Xcode ]; then

    if [ $1 = true ]; then
      printf '\033[0;34m%s\033[0m\n' "Start setting up Xcode..."
    else
      printf '\033[0;34m%s\033[0m\n' "Updating Xcode preferences..."
    fi

    deldir $XcodeKeys
    ln -s $dotfiles/Xcode/UserData/KeyBindings		$XcodeKeys

    deldir $XcodeThemes
    ln -s $dotfiles/Xcode/UserData/FontAndColorThemes	$XcodeThemes

    deldir ${XcodeTemplates}
    ln -s "$dotfiles/Xcode/Templates"                   $XcodeTemplates

  fi
}

echo "\n======================================================================"
printf '\033[0;34m%s\033[0m\n' "Setting up preferences..."

if [ ! -d $dotfiles ]; then
  # setup a brand new system
  git clone git://github.com/robbyrussell/oh-my-zsh.git $zsh
  git clone $repos $dotfiles

  # zsh (as dotfiles's submodule)
  printf '\033[0;34m%s\033[0m\n' "Setting up ZSH..."
  export ZSH="$zsh"
  chsh -s /bin/zsh
  link $dotfiles/shell/zshrc	$HOME/.zshrc
  printf "\e[32m[✔]\e[0m Successfully installed ZSH."
  echo "======================================================================"

  # tmux
  printf '\033[0;34m%s\033[0m\n' "Setting up TMUX..."
  link $dotfiles/tmux/tmux.conf             $HOME/.tmux.conf

  # dev
  printf '\033[0;34m%s\033[0m\n' "Setting up git & ssh..."
  link $dotfiles/git/gitconfig        $HOME/.gitconfig
  link $dotfiles/git/gitignore_global $HOME/.gitignore_global
  if [ ! -d "$HOME/.ssh" ]; then
    mkdir $HOME/.ssh
  fi
  link $dotfiles/ssh/config     $HOME/.ssh/config

  setup_xcode true
#================================================================================
else
  cd $dotfiles
  printf '\033[0;34m%s\033[0m\n' "Updating Preferences..."
  git pull

  # zsh
  printf '\033[0;34m%s\033[0m\n' "Updating zsh..."
  git pull
  cd $zsh
  git pull
  link $dotfiles/shell/zshrc	$HOME/.zshrc

  link $dotfiles/tmux/tmux.conf             $HOME/.tmux.conf

  link $dotfiles/git/gitconfig        $HOME/.gitconfig
  link $dotfiles/git/gitignore_global $HOME/.gitignore_global
  if [ ! -d "$HOME/.ssh" ]; then
    mkdir $HOME/.ssh
  fi
  link $dotfiles/ssh/config     $HOME/.ssh/config

  setup_xcode false
fi
