# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export LC_ALL="en_US.UTF-8"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="avit"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(colorize command-not-found cp git golang osx python svn)

# Automatically update ZSH without prompting
DISABLE_UPDATE_PROMPT=true

source $ZSH/oh-my-zsh.sh
source "$HOME/.files/zsh/functions.zsh"
source "$HOME/.files/zsh/env.zsh"
if [ -f "$HOME/.env.local" ]; then
    source "$HOME/.env.local"
fi

ZSH_TMUX_AUTOSTART=false
ZSH_TMUX_AUTOSTART_ONCE=true
alias mx=tmuxinator

##------------------------------
## Growl for Notification Center
##------------------------------
function notice() {
  if [ -x "/usr/local/bin/terminal-notifier" ]; then
    terminal-notifier -activate com.googlecode.iterm2 -title "iTerm2" -message "$@"
    say "$@"
  fi
}

##-------------------
## direnv
##-------------------
eval "$(direnv hook zsh)"


# ============================================================
#  ALIASES AND FUNCTIONS
# ------------------------------------------------------------
#  Arguably, some functions defined here are quite big.
#  If you want to make this file smaller, these functions can
# be converted into scripts and removed from here.
# ============================================================
alias vi="vim"
#alias vim='vim --servername vim'

##-------------------
## Personnal Aliases
##-------------------
alias e="emacs"
alias emacs="emacs -nw"
alias rm="trash"
alias ag="ag --page=less"
alias du="du -sh"
alias got="go get -v"
alias pkg="npm install --verbose"
alias xcode='open *.xcworkspace'
alias lstcp="lsof -i -n -P | grep TCP"
alias lsudp="lsof -i -n -P | grep UDP"
if [ -x /usr/local/bin/ipython ]; then
  alias ip="ipython"
fi
if [ -x /usr/local/bin/gls ]; then
  alias ls="gls --color=auto --group-directories-first"
fi
alias ll="ls -l --ignore=build --ignore=node_modules"
##-------------------
## Golang Aliases
##-------------------

